blank_issues_enabled: false
contact_links:
  - name: Wiki do projeto
    url: https://github.com/HugoTorquetti/portifolio-pessoal-mentoria/wiki
    about: Consulte a documentação funcional e de qualidade do projeto.
